-- MySQL Script generated by MySQL Workbench
-- 11/12/16 14:28:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Ships`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ships` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Ships` (
  `Ship_id` INT NOT NULL,
  `Ship_Name` VARCHAR(45) NOT NULL,
  `Ship_Details` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Ship_id`),
  UNIQUE INDEX `Ship_id_UNIQUE` (`Ship_id` ASC),
  UNIQUE INDEX `Ship_Name_UNIQUE` (`Ship_Name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Routes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Routes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Routes` (
  `Route_Number` INT NOT NULL,
  `Route_Duration` INT NOT NULL,
  PRIMARY KEY (`Route_Number`),
  UNIQUE INDEX `Route_Number_UNIQUE` (`Route_Number` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cruises`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cruises` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cruises` (
  `Cruise_id` INT NOT NULL,
  `Route_id` INT NOT NULL,
  `Cruise_Start_Date` DATE NOT NULL,
  `Ship_id` INT NOT NULL,
  PRIMARY KEY (`Cruise_id`),
  INDEX `Ships_idx` (`Ship_id` ASC),
  INDEX `Routes_idx` (`Route_id` ASC),
  UNIQUE INDEX `Cruise_id_UNIQUE` (`Cruise_id` ASC),
  CONSTRAINT `Ships`
    FOREIGN KEY (`Ship_id`)
    REFERENCES `mydb`.`Ships` (`Ship_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Routes`
    FOREIGN KEY (`Route_id`)
    REFERENCES `mydb`.`Routes` (`Route_Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Positions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Positions` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Positions` (
  `Position_ID` INT NOT NULL,
  `Position_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Position_ID`),
  UNIQUE INDEX `Permission_ID_UNIQUE` (`Position_ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Staff` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Staff` (
  `Staff_ID` INT NOT NULL,
  `First_Name` VARCHAR(45) NOT NULL,
  `Last_Name` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `Phone_Number` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Position_ID` INT NULL,
  PRIMARY KEY (`Staff_ID`),
  INDEX `Position_ID_idx` (`Position_ID` ASC),
  CONSTRAINT `Position_ID`
    FOREIGN KEY (`Position_ID`)
    REFERENCES `mydb`.`Positions` (`Position_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cruises_Staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cruises_Staff` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cruises_Staff` (
  `Cruise_id` INT NOT NULL,
  `Staff_ID` INT NOT NULL,
  PRIMARY KEY (`Cruise_id`, `Staff_ID`),
  INDEX `fk_Cruises_has_Staff_Staff1_idx` (`Staff_ID` ASC),
  INDEX `fk_Cruises_has_Staff_Cruises1_idx` (`Cruise_id` ASC),
  CONSTRAINT `fk_Cruises_has_Staff_Cruises1`
    FOREIGN KEY (`Cruise_id`)
    REFERENCES `mydb`.`Cruises` (`Cruise_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cruises_has_Staff_Staff1`
    FOREIGN KEY (`Staff_ID`)
    REFERENCES `mydb`.`Staff` (`Staff_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rooms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Rooms` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Rooms` (
  `Room_Number` INT NOT NULL,
  `Room_Type` VARCHAR(45) NOT NULL,
  `Ship_ID` INT NOT NULL,
  PRIMARY KEY (`Room_Number`, `Ship_ID`),
  INDEX `Ship_ID_idx` (`Ship_ID` ASC),
  CONSTRAINT `Ship_ID`
    FOREIGN KEY (`Ship_ID`)
    REFERENCES `mydb`.`Ships` (`Ship_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Facility`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Facility` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Facility` (
  `Facility_ID` INT NOT NULL,
  `Facility_Name` VARCHAR(45) NOT NULL,
  `Room_Number` INT NULL,
  PRIMARY KEY (`Facility_ID`),
  INDEX `Room Number_idx` (`Room_Number` ASC),
  CONSTRAINT `Room_Number`
    FOREIGN KEY (`Room_Number`)
    REFERENCES `mydb`.`Rooms` (`Room_Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Schedule` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Schedule` (
  `Shift_StartDate` DATE NOT NULL,
  `Shift_StartTime` TIME NOT NULL,
  `Shift_Duration` TIME NOT NULL,
  `Staff_ID` INT NOT NULL,
  `Facility_ID` INT NOT NULL,
  `Position_ID` INT NOT NULL,
  INDEX `Facility_ID_idx` (`Facility_ID` ASC),
  INDEX `Staff_ID_idx` (`Staff_ID` ASC),
  PRIMARY KEY (`Shift_StartTime`, `Staff_ID`, `Shift_StartDate`),
  INDEX `Position_ID_idx` (`Position_ID` ASC),
  CONSTRAINT `Staff_ID`
    FOREIGN KEY (`Staff_ID`)
    REFERENCES `mydb`.`Cruises_Staff` (`Staff_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Facility_ID`
    FOREIGN KEY (`Facility_ID`)
    REFERENCES `mydb`.`Facility` (`Facility_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Position_ID`
    FOREIGN KEY (`Position_ID`)
    REFERENCES `mydb`.`Positions` (`Position_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Travellers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Travellers` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Travellers` (
  `TVL_ID` INT NOT NULL,
  `TVL_Name` VARCHAR(45) NOT NULL,
  `TVL_Address` VARCHAR(45) NOT NULL,
  `TVL_Phone_Number` VARCHAR(45) NOT NULL,
  `TVL_Email` VARCHAR(45) NOT NULL,
  `TVL_DOB` DATE NOT NULL,
  `TVL_Gender` CHAR NOT NULL,
  PRIMARY KEY (`TVL_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Booking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Booking` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Booking` (
  `Cruise_ID` INT NOT NULL,
  `Traveller_ID` INT NOT NULL,
  PRIMARY KEY (`Cruise_ID`, `Traveller_ID`),
  INDEX `Traveller_ID_idx` (`Traveller_ID` ASC),
  CONSTRAINT `Traveller_ID`
    FOREIGN KEY (`Traveller_ID`)
    REFERENCES `mydb`.`Travellers` (`TVL_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Cruise_ID`
    FOREIGN KEY (`Cruise_ID`)
    REFERENCES `mydb`.`Cruises` (`Cruise_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Port`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Port` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Port` (
  `Port_id` INT NOT NULL,
  `Port_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Port_id`),
  UNIQUE INDEX `Port_id_UNIQUE` (`Port_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Stops`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Stops` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Stops` (
  `Route_Number` INT NOT NULL,
  `Port_id` INT NOT NULL,
  `Stop_SequenceNumber` INT NOT NULL,
  `Stop_Duration` TIME NOT NULL,
  PRIMARY KEY (`Route_Number`, `Port_id`),
  INDEX `fk_Routes_has_Port_Port1_idx` (`Port_id` ASC),
  INDEX `fk_Routes_has_Port_Routes1_idx` (`Route_Number` ASC),
  CONSTRAINT `fk_Routes_has_Port_Routes1`
    FOREIGN KEY (`Route_Number`)
    REFERENCES `mydb`.`Routes` (`Route_Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Routes_has_Port_Port1`
    FOREIGN KEY (`Port_id`)
    REFERENCES `mydb`.`Port` (`Port_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Products` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Products` (
  `Prod_ID` INT NOT NULL,
  `Prod_Name` VARCHAR(45) NOT NULL,
  `Prod_Price` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Prod_ID`),
  UNIQUE INDEX `Prod_ID_UNIQUE` (`Prod_ID` ASC),
  UNIQUE INDEX `Prod_Name_UNIQUE` (`Prod_Name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Purchases`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Purchases` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Purchases` (
  `Room_Num` INT NOT NULL,
  `Prod_ID` INT NOT NULL,
  `Purchase_Quantity` INT NOT NULL,
  `Purchase_Date` DATE NOT NULL,
  `Purchase_Time` TIME NOT NULL,
  `Facility_ID` INT NOT NULL,
  `Purchase_Number` INT NOT NULL,
  PRIMARY KEY (`Purchase_Number`),
  INDEX `Prod_ID_idx` (`Prod_ID` ASC),
  INDEX `Facility_ID_idx` (`Facility_ID` ASC),
  UNIQUE INDEX `Purchase_Number_UNIQUE` (`Purchase_Number` ASC),
  CONSTRAINT `Room_Num`
    FOREIGN KEY (`Room_Num`)
    REFERENCES `mydb`.`Rooms` (`Room_Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Prod_ID`
    FOREIGN KEY (`Prod_ID`)
    REFERENCES `mydb`.`Products` (`Prod_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Facility_ID`
    FOREIGN KEY (`Facility_ID`)
    REFERENCES `mydb`.`Facility` (`Facility_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
