using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace ClientServerProject
{
    public partial class PlanPayment : UserControl
    {
        Plan plan;
        PlanSearch ps;
        PlanGuestInformation planguestinfo;
        int cruiseid;
        string roomnum;
        List<Guest> guestinfo;
        List<string> temp = new List<string>();
        List<string> custId = new List<string>();
        CommandProcessor cp = new CommandProcessor();
        int pplInRoom;
        string shipid;
        public PlanPayment(Plan p,PlanGuestInformation pgi,int ci,string rn,List<Guest>gi)
        {
            InitializeComponent();
            plan = p;
            planguestinfo = pgi;
            cruiseid = ci;
            roomnum = rn;
            guestinfo = gi;
        }

        private void button1_Click(object sender, EventArgs e)
        {
            //------add customers info
            string query = "INSERT INTO Travellers VALUES(null, @fname, @lname, @addr, @phone, @email, @dob, @gender)";
            for (int x = 0; x < guestinfo.Count(); x++)
            {
                temp.Clear();
                temp.Add(guestinfo[x].fName);
                temp.Add(guestinfo[x].lName);
                temp.Add(guestinfo[x].addr);
                temp.Add(guestinfo[x].pNum);
                temp.Add(guestinfo[x].email);
                temp.Add(guestinfo[x].toDOB());
                temp.Add(guestinfo[x].gender.ToString());
                cp.insertRec(query, temp);
                //------get customer autogenerated id
                string cid = "select TVL_ID from Travellers where TVL_FName=@fname and TVL_LName=@lname and TVL_Address=@addr and TVL_Phone_Number=@phone and TVL_Email=@email and TVL_DOB=@dob and TVL_Gender=@gender";
                custId.Add(cp.getCId(cid, temp));
            }
            //------add booking info
            query = "INSERT INTO Booking VALUES(@cruise,@tvlr,@room)";
            for(int y = 0; y < guestinfo.Count(); y++)
            {
                temp.Clear();
                temp.Add(cruiseid.ToString());
                temp.Add(custId[y]);
                temp.Add(roomnum);
                cp.insertRec(query, temp);
            }
            //------determine how many ppl reside in roomnum
            //------determine whether to change isOccupied to '1'
            query = "select Count(Traveller_Id) from Booking where Cruise_ID=@cruise and Room_Number=@room";
            pplInRoom = cp.getPplInRoom(query, cruiseid.ToString(), roomnum);
            //find ship id given cruise id
            query = "select Ship_id from Cruises where Cruise_id=@cruise";
            shipid = cp.getSId(query, cruiseid);
            query = "update Rooms set isOccupied='1' where Room_Number=@room and Ship_ID=@ship";
            if (pplInRoom == 4)
            {
                cp.updateRec(query, roomnum, shipid);
            }
            MessageBox.Show("Payment successful, thank you for cruising with us");
            PlanSearch ps = new PlanSearch(plan);
            plan.Controls.Add(ps);
            plan.Controls.Remove(this);
        }
    }
}
